version: "3"
services:
  php:
    hostname: php
    restart: always
    container_name: php
    privileged: true
    build:
      context: ./
      dockerfile: Dockerfile
    expose:
      - "9000"
    depends_on:
      - mysql
    volumes:
      - ./www/:/var/www/html/
      #- ./php/config/:/usr/local/etc
    # 设置网络
    networks:
      - web

  mysql:
    hostname: mysql
    restart: always
    image: mysql:5.6
    container_name: mysql
    ports:
      - "3306:3306"
    #expose:
      #- "3306"
    # volumes:
    #   - ./mysql/config:/etc/mysql
    #   - ./mysql/log:/var/log/mysql
    #   - ./mysql/data:/var/lib/mysql
    environment:
      - TZ=Asia/Shanghai # 设置时区
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user123
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci # 设置编码
    networks:
      # 指定网络ip
      web:
        ipv4_address: 172.16.1.2
  
  nginx:
    hostname: nginx
    restart: always
    container_name: nginx
    # 设置特权，避免权限不够的情况
    privileged: true
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php
    volumes:
      - ./www/:/var/www/html/
      - ./nginx/config/:/etc/nginx/:ro
      - ./nginx/log/:/var/log/nginx/
    networks:
      - web

networks:
  # 设置网络模式及网段
  web:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.1.0/24
