version: '2'
services:
  web:
    hostname: web
    image: httpd
    container_name: web
    ports:
      - "80:80"
    links:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: httpd.access

  fluentd:
    hostname: fluentd
    build: ./fluentd
    privileged: true
    container_name: fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    hostname: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
    privileged: true
    container_name: elasticsearch
    volumes:
      - ./es/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      # - ./es/data:/usr/share/elasticsearch/data
    expose:
      - 9200
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    hostname: kibana
    image: docker.elastic.co/kibana/kibana:7.4.2
    privileged: true
    container_name: kibana
    links:
      - "elasticsearch"
    volumes:
      - ./kibana/plugins/:/usr/share/kibana/plugins/
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"