version: '3'
services:
  mongo:
    image: mongo:4.1.6
    ports:
      - 27017:27017
    restart: always
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
